[package]
name = "tetro-tui"
version = "3.6.1"
edition = "2024"
rust-version = "1.90.0"
authors = ["Strophox"]
license = "MIT"
description = "Terminal-based but modern tetromino-stacking game that is customizable and cross-platform."
# documentation = "https://docs.rs/tetro-tui"
# homepage = "https://...
repository = "https://github.com/Strophox/tetro-tui"
readme = "README.md"
keywords = ["tetromino", "terminal", "game", "tui", "ascii-art"]
categories = ["games", "command-line-utilities"]
exclude = ["demo_assets/*", ".github/", "RELEASE-CHECKLIST.md", "flake.nix", "flake.lock"]


[profile.release]
strip = true  # Automatically strip symbols from the binary.
# opt-level = "z"  # Optimize for size.
# lto = true # Enable link-time optimization.
# codegen-units = 1 # Use fewer than 16 threads for compilation, but enable some optimizations.

[dependencies]
bitflags = { version = "2.11.1", features = ["serde"] }
chrono = "0.4.38" # = Used to generate timestamps.
clap = { version = "4.5.9", features = ["derive", "wrap_help"] } # = Used to handle command-line arguments.
crossterm = { version = "0.29.0", features = ["serde"] } # = Use for cross-platform terminal handling.
dirs = "6.0.0" # = Used for cross-platform "find the standard applications-config folder" functionality.
either = "1.15.0" # = Basic enum.
rand = "0.10.0" # = Base random functionality.

serde = { version = "1.0.204", features = ["derive"] }
serde_with = { version = "3.9.0" }#, features = ["json"] } # = Use to configure serialization details.
# serde_json = "1.0.120"
# json5 = "1.3.1"
# serde_yaml = "0.9.34"
# toml = "1.1.2"
ron = "0.12.1" # = Used to serialize in Rusty Object Notation.

falling-tetromino-engine = { version = "12.0.0", features = ["serde"] } # = Core game logic.
# falling-tetromino-engine = { path = "../falling-tetromino-engine", features = ["serde"] } # = Dev. Core game logic.
